version: '3.1'

services:
  database:
    image: 'bitnami/postgresql:latest'
    ports:
    - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api-healthy-plan
    networks:
      - my-network

  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://root:docker@database:5432/api-healthy-plan
      - NODE_ENV=dev

    depends_on:
      - database
    command: ["./migration.sh"]
    networks:
    - my-network

networks:
  my-network:
    driver: bridge


