version: '3.1'

services:
    database:
        image: 'bitnami/postgresql:latest'
        ports:
        - 5432:5432
        restart: always
        environment:
        - POSTGRESQL_USERNAME=root
        - POSTGRESQL_PASSWORD=docker
        - POSTGRESQL_DATABASE=api-healthy-plan
        networks:
        - my-network

    redis:
        image: 'redis:latest'
        ports:
        - 6379:6379
        restart: always
        networks:
        - my-network

    api:
        build: .
        ports:
        - 3000:3000
        restart: always
        environment:
        - DATABASE_URL=postgresql://root:docker@database:5432/api-healthy-plan
        - CACHE_URL=redis://redis:6379
        - PORT=3000

        depends_on:
        - database
        - redis
        networks:
        - my-network

networks:
    my-network:
        driver: host
