name: Run E2E Tests

on:
    push:
      branches:
        - main
        - dev

jobs:

  run-E2E-tests:
    runs-on: ubuntu-latest

    services:
      database:
        image: 'bitnami/postgresql:latest'
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: root
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: api-healthy-plan

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        env:
            DATABASE_URL: postgresql://root:docker@database:5432/api-healthy-plan
        with:
          node-version: '18.x'

      - run: npm ci

      - run: npm run prisma:generate

      - run: npm run prisma:deploy

      - run: npm run test:e2e
